services:
  ghost:
    image: ghost:5-alpine
    container_name: ghost
    restart: always
    expose:
      - "2368"
    environment:
      url: ${GHOST_URL}
      database__client: mysql2
      database__connection__host: ${DB_HOST}
      database__connection__port: ${DB_PORT}
      database__connection__user: ${DB_USER}
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ${DB_NAME}
      # 외부 로드 밸런서 사용시 필요한 설정
      server__host: 0.0.0.0
      server__port: 2368
    volumes:
      - ./data/ghost:/var/lib/ghost
    networks:
      - ghost-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - ghost
    networks:
      - ghost-network

networks:
  ghost-network:
    driver: bridge
