version: '3.8'

services:
  ghost:
    image: ghost:5-alpine
    container_name: ghost
    restart: always
    ports:
      - "2368:2368"
    environment:
      url: http://leecod.ing
    volumes:
      - ./content:/var/lib/ghost/content
